### PR TITLE
Upgrading rubyzip to 1.0.0

### PR DESCRIPTION
**Pull request by deCasale**
Zippy does not work with rubyzip 1.0.0 so it's either this or changing the dependency to < 1.0.0

### CODE REVIEW

**Comment by toretore** [comment]
Thanks again.

**Comment by queencity13** [comment]
Will there be a 0.3 release with this issue in it?

**Comment by deCasale** [comment]
That'd be great

**Comment by jawj** [comment]
+1 for a rubygems release!

**Pull request merged**
